"""add request metadata to audit_logs

Revision ID: 288f910ba56d
Revises: 5d676ed97da0
Create Date: 2026-02-23 03:17:35.420381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288f910ba56d'
down_revision = '5d676ed97da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referrer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('referrer')
        batch_op.drop_column('path')
        batch_op.drop_column('method')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
