"""add ip_address to audit_logs

Revision ID: 5d676ed97da0
Revises: b3c2d1e4f5a6
Create Date: 2026-02-23 03:04:33.903280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d676ed97da0'
down_revision = 'b3c2d1e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
