"""add_whatsapp_link_to_groups

Revision ID: bbf8fd4d3a81
Revises: 288f910ba56d
Create Date: 2026-02-23 01:09:13.657864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf8fd4d3a81'
down_revision = '288f910ba56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_link')

    # ### end Alembic commands ###
